### ISSUE TITLE
can not compile on Ubuntu18.04 gcc7.5

### ISSUE THREAD

**Issue by DingFeng9313** [Jaybro/pico_tree#32]
get Error while compiling examples

```
pico_tree/kd_tree.hpp:362:13: error: ‘pico_tree::KdTree<Space_, Metric_, SplittingRule_, Index_>::space_’ has incomplete type
   SpaceType space_
```

on ubuntu18.04, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
using cxx standard 17

**Comment by DingFeng9313** [comment]
There are some modified config. Since my cmake version is 3.10. And I don't want to install latest cmake.

So I made following changes, I suppose it wouldn't impact
![Screenshot from 2023-09-07 15-16-24](https://github.com/Jaybro/pico_tree/assets/73571905/f33ce0c5-89dc-4fe7-9221-7139abb6e06c)

**Comment by DingFeng9313** [comment]
looks like it is "reference_wrapper" problem, my c++ 17 also doesn't include filesystem, so I have to add "experimental::filesystem"

case closed. Thank you for sharing your excellent work

**Comment by Jaybro** [comment]
Thank you for reporting the missing include! I will add a fix for that.

**Comment by Jaybro** [comment]
I created release v0.8.2 that adds a fix for the missing include. This release does use `#include <filesystem>` a bit more, so you may need to use `experimental` a few extra times with the older GCC.

Thanks again!
